AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: YouTube AI Clipper - Professional Demo

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.10

Resources:
  VideoAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handlers.video_handler.lambda_handler
      Description: Analyzes YouTube videos for topic mentions
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        VideoAnalysisApi:
          Type: Api
          Properties:
            Path: /analyze
            Method: post
            
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handlers.video_handler.lambda_handler
      Description: Health check endpoint
      Events:
        HealthCheckApi:
          Type: Api
          Properties:
            Path: /health
            Method: get

Outputs:
  ApiGatewayUrl:
    Description: URL of the API Gateway
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
      
  VideoAnalysisEndpoint:
    Description: Video Analysis Endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze"
    
  HealthCheckEndpoint:
    Description: Health Check Endpoint  
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/health"
