AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: YouTube AI Clipper - With Optional Real Transcription

Globals:
  Function:
    Timeout: 180
    MemorySize: 1024
    Runtime: python3.10

Parameters:
  YouTubeApiKey:
    Type: String
    Description: YouTube Data API v3 Key
    Default: "AIzaSyAsZceUU693rWYz1cuXSSzQbHKlM4gBGfU"
    NoEcho: true

Resources:
  VideoAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handlers.video_handler.lambda_handler
      Description: Analyzes YouTube videos with intelligent transcription fallbacks
      Environment:
        Variables:
          YOUTUBE_API_KEY: !Ref YouTubeApiKey
          # OpenAI key will be detected from local environment if available
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        VideoAnalysisApi:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

Outputs:
  VideoAnalysisEndpoint:
    Description: Video Analysis Endpoint with Intelligent Transcription
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze"
