AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: YouTube AI Clipper - With AWS Transcribe Integration

Globals:
  Function:
    Timeout: 180
    MemorySize: 1024
    Runtime: python3.10

Parameters:
  YouTubeApiKey:
    Type: String
    Description: YouTube Data API v3 Key
    Default: "AIzaSyAsZceUU693rWYz1cuXSSzQbHKlM4gBGfU"
    NoEcho: true

Resources:
  TranscriptionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "youtube-ai-clipper-transcription-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: CleanupTempFiles
            Status: Enabled
            ExpirationInDays: 1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  VideoAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handlers.video_handler.lambda_handler
      Description: Analyzes YouTube videos with AWS Transcribe
      Layers:
        - arn:aws:lambda:us-east-1:767242440716:layer:ffmpeg-layer:2
      Environment:
        Variables:
          YOUTUBE_API_KEY: !Ref YouTubeApiKey
          TRANSCRIPTION_BUCKET: !Ref TranscriptionBucket
          PATH: "/opt/bin:/var/lang/bin:/usr/local/bin:/usr/bin:/bin"
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource:
                - !Sub "arn:aws:s3:::${TranscriptionBucket}/*"
                - !Sub "arn:aws:s3:::${TranscriptionBucket}"
            - Effect: Allow
              Action:
                - transcribe:StartTranscriptionJob
                - transcribe:GetTranscriptionJob
                - transcribe:DeleteTranscriptionJob
              Resource: "*"
      Events:
        VideoAnalysisApi:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

  EnvironmentDiagnosticFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handlers.environment_diagnostic.lambda_handler
      Description: Check Lambda environment capabilities
      Layers:
        - arn:aws:lambda:us-east-1:767242440716:layer:ffmpeg-layer:2
      Environment:
        Variables:
          TRANSCRIPTION_BUCKET: !Ref TranscriptionBucket
          PATH: "/opt/bin:/var/lang/bin:/usr/local/bin:/usr/bin:/bin"
      Events:
        EnvironmentDiagnosticApi:
          Type: Api
          Properties:
            Path: /environment
            Method: get

Outputs:
  VideoAnalysisEndpoint:
    Description: Video Analysis Endpoint with AWS Transcribe
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze"
    
  TranscriptionBucket:
    Description: S3 Bucket for transcription files
    Value: !Ref TranscriptionBucket

  EnvironmentDiagnosticEndpoint:
    Description: Environment Diagnostic Endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/environment"
