AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: YouTube AI Clipper - Initial Deployment

Resources:
  YouTubeDownloaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: package/
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          YOUTUBE_API_KEY: "AIzaSyAsZceUU693rWYz1cuXSSzQbHKlM4gBGfU"
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /video-info
            Method: post

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/video-info"