AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: YouTube AI Clipper - Debug Mode

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.10

Parameters:
  YouTubeApiKey:
    Type: String
    Description: YouTube Data API v3 Key
    Default: "AIzaSyAsZceUU693rWYz1cuXSSzQbHKlM4gBGfU"
    NoEcho: true

Resources:
  VideoAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/
      Handler: handlers.debug_handler.lambda_handler
      Description: Debug handler to identify issues
      Environment:
        Variables:
          YOUTUBE_API_KEY: !Ref YouTubeApiKey
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        VideoAnalysisApi:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

Outputs:
  VideoAnalysisEndpoint:
    Description: Video Analysis Endpoint (Debug Mode)
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze"
